name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -r requirements.txt
      
      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Execute tests
        run: python3 -m pytest -s -v tests